// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7wvMDWlytMybcubd_qsptl-ZJDA3XjgU',
    appId: '1:605278579284:web:65bb619ab766e37ea29bc1',
    messagingSenderId: '605278579284',
    projectId: 'ups-clone-c16f4',
    authDomain: 'ups-clone-c16f4.firebaseapp.com',
    storageBucket: 'ups-clone-c16f4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtSSdiB5fFSmT7QVsaMaWZu4prEYy3xuQ',
    appId: '1:605278579284:android:6c42086d7f31f17aa29bc1',
    messagingSenderId: '605278579284',
    projectId: 'ups-clone-c16f4',
    storageBucket: 'ups-clone-c16f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8P5ffGSPQlXeS8Subdkb1cvEm6KB0VCI',
    appId: '1:605278579284:ios:366ef5d208cf01dfa29bc1',
    messagingSenderId: '605278579284',
    projectId: 'ups-clone-c16f4',
    storageBucket: 'ups-clone-c16f4.appspot.com',
    iosClientId: '605278579284-ejblpia3ptuafj4b6u6qtuntgmnflok6.apps.googleusercontent.com',
    iosBundleId: 'com.example.upsClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8P5ffGSPQlXeS8Subdkb1cvEm6KB0VCI',
    appId: '1:605278579284:ios:366ef5d208cf01dfa29bc1',
    messagingSenderId: '605278579284',
    projectId: 'ups-clone-c16f4',
    storageBucket: 'ups-clone-c16f4.appspot.com',
    iosClientId: '605278579284-ejblpia3ptuafj4b6u6qtuntgmnflok6.apps.googleusercontent.com',
    iosBundleId: 'com.example.upsClone',
  );
}
